name: fit_tool
description: A library for reading and writing Garmin FIT files. The Flexible and Interoperable Data Transfer (FIT) protocol is a standard for storing fitness activities, courses, and workouts.
version: 1.0.2
repository: https://bitbucket.org/stagescycling/fit_tool

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  csv: ^5.0.0
  logger: ^1.1.0
  fixnum: ^1.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  gpx: ^2.1.0
  haversine_distance: ^1.2.1
  http: ^0.13.4
  shelf: ^1.3.1
  shelf_cors_headers: ^0.1.3
  stream_channel: ^2.1.0
  lints: ^2.0.0
